# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

platform:ios, '7.0'
target 'CoMoBicycle' do

pod 'AFNetworking'
pod 'Masonry'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'MMDrawerController'
pod 'IQKeyboardManager'
pod 'PYSearch'
pod 'DZNEmptyDataSet'



# react-native
pod 'React', :path => '../node_modules/react-native', :subspecs =>[

    'Core',
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTSettings',
    'RCTVibration',
    'RCTGeolocation',
    'RCTWebSocket',
    'RCTActionSheet',
]

pod'CodePush',:path => '../node_modules/react-native-code-push'

end
